# Generated by Django 5.0.3 on 2024-05-29 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Album')),
                ('name', models.CharField(max_length=200, verbose_name='Tên Album')),
                ('artist_name', models.CharField(max_length=200, verbose_name='Tên Ca Sĩ Album')),
                ('image', models.ImageField(upload_to='album_images/', verbose_name='Hình Album')),
            ],
            options={
                'verbose_name': 'Album',
                'verbose_name_plural': 'Các Album',
            },
        ),
        migrations.CreateModel(
            name='Chude',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Chủ đề')),
                ('name', models.CharField(max_length=200, verbose_name='Tên chủ đề')),
                ('image', models.ImageField(upload_to='chude_images/', verbose_name='Hình chủ đề')),
            ],
            options={
                'verbose_name': 'Chủ đề',
                'verbose_name_plural': 'Các chủ đề',
            },
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Playlist')),
                ('name', models.CharField(max_length=200, verbose_name='Tên Playlist')),
                ('image', models.ImageField(upload_to='playlist_images/', verbose_name='Hình Playlist')),
                ('icon', models.ImageField(upload_to='playlist_icons/', verbose_name='Hình Icon')),
            ],
            options={
                'verbose_name': 'Playlist',
                'verbose_name_plural': 'Các Playlists',
            },
        ),
        migrations.AddField(
            model_name='sanpham',
            name='category',
            field=models.ManyToManyField(related_name='product', to='app.category'),
        ),
        migrations.CreateModel(
            name='Baihat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Bài hát')),
                ('ten', models.CharField(max_length=200, verbose_name='Tên Bài hát')),
                ('hinh', models.ImageField(upload_to='baihat_images/', verbose_name='Hình Bài hát')),
                ('casi', models.CharField(max_length=200, verbose_name='Ca sĩ')),
                ('link', models.URLField(verbose_name='Link Bài hát')),
                ('luotthich', models.IntegerField(default=0, verbose_name='Lượt thích')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.album', verbose_name='ID Album')),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.playlist', verbose_name='ID Playlist')),
            ],
            options={
                'verbose_name': 'Bài hát',
                'verbose_name_plural': 'Các Bài hát',
            },
        ),
        migrations.CreateModel(
            name='Quangcao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Quảng cáo')),
                ('image', models.ImageField(upload_to='banner_images/', verbose_name='Hình Quảng cáo')),
                ('content', models.TextField(verbose_name='Nội dung Quảng cáo')),
                ('baihat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.baihat', verbose_name='ID Bài hát')),
            ],
            options={
                'verbose_name': 'Quảng cáo',
                'verbose_name_plural': 'Các Quảng cáo',
            },
        ),
        migrations.CreateModel(
            name='Theloai',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Thể loại')),
                ('name', models.CharField(max_length=200, verbose_name='Tên thể loại')),
                ('image', models.ImageField(upload_to='theloai_images/', verbose_name='Hình thể loại')),
                ('chude', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.chude', verbose_name='ID Chủ đề')),
            ],
            options={
                'verbose_name': 'Thể loại',
                'verbose_name_plural': 'Các thể loại',
            },
        ),
        migrations.AddField(
            model_name='baihat',
            name='theloai',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.theloai', verbose_name='ID Thể loại'),
        ),
    ]
