# Generated by Django 5.0.3 on 2024-06-03 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_yeuthichnhieu_sampham_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
