# Generated by Django 5.0.3 on 2024-06-05 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_baihat_hinh_baihat_image_alter_album_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baihat',
            name='link',
        ),
        migrations.AddField(
            model_name='baihat',
            name='file',
            field=models.FileField(blank=True, default='', null=True, upload_to='audios/'),
        ),
    ]
