# Generated by Django 5.0.3 on 2024-06-15 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_file_baihat_audio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quangcao',
            name='content',
        ),
    ]
