# Generated by Django 5.0.3 on 2024-06-15 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_chude_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='chude',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
