# Generated by Django 5.0.3 on 2024-06-15 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_chude_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='artist_name',
            new_name='casi',
        ),
        migrations.RemoveField(
            model_name='chude',
            name='image',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='image',
        ),
        migrations.RemoveField(
            model_name='theloai',
            name='image',
        ),
    ]
