# Generated by Django 5.0.3 on 2024-06-16 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_baihat_chude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baihat',
            name='chude',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='baihats', to='app.chude', verbose_name='Chủ đề'),
        ),
    ]
