# Generated by Django 5.0.3 on 2024-06-16 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_baihat_chude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baihat',
            name='chude',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.chude', verbose_name='Chủ đề'),
            preserve_default=False,
        ),
    ]
