# Generated by Django 5.0.3 on 2024-06-16 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_baihat_chude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baihat',
            name='chude',
        ),
    ]
