# Generated by Django 5.0.3 on 2024-06-18 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_remove_baihat_chude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='icon',
        ),
        migrations.AddField(
            model_name='playlist',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
