# Generated by Django 5.0.3 on 2024-06-18 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_remove_playlist_icon_playlist_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='image',
        ),
    ]
