# Generated by Django 5.0.3 on 2024-06-18 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_playlist_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='theloai',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
